# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [4]:
# No code solution (reading)
## some stuff in torch.tensor documentation
import torch
tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(f"normal:{tensor}, reverse:{tensor.T}, h:{tensor.H}")

normal:tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), reverse:tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]]), h:tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


### 2. Create a random tensor with shape `(7, 7)`.


In [8]:
# Import torch
t = torch.rand(7,7)
t

# Create random tensor


tensor([[0.3453, 0.3199, 0.3753, 0.3202, 0.5059, 0.0165, 0.7406],
        [0.9554, 0.8346, 0.2724, 0.0277, 0.7730, 0.3257, 0.8200],
        [0.5698, 0.8561, 0.6702, 0.7292, 0.1482, 0.1621, 0.5957],
        [0.0941, 0.2328, 0.2971, 0.7899, 0.0582, 0.5350, 0.2760],
        [0.2782, 0.3035, 0.0337, 0.3562, 0.0478, 0.2220, 0.9257],
        [0.6426, 0.3413, 0.8757, 0.0100, 0.6964, 0.2531, 0.3153],
        [0.5640, 0.1976, 0.8602, 0.7329, 0.8201, 0.0715, 0.3305]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [13]:
# Create another random tensor
x = torch.rand(1,7)
# Perform matrix multiplication 
ans = torch.matmul(t,x.T)
ans

tensor([[1.8207],
        [2.5085],
        [2.1893],
        [1.2485],
        [1.3699],
        [2.1525],
        [2.3343]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [22]:
# Set manual seed
random_seed = 0

# Create two random tensors
torch.manual_seed(random_seed)
t = torch.rand(7,7)
print(t)
torch.manual_seed(random_seed)
x = torch.rand(1,7)
print(x)
# Matrix multiply tensors
torch.matmul(t,x.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [21]:
# Set manual seed
random_seed = 0

# Create two random tensors
torch.manual_seed(random_seed)
t = torch.rand(7,7)
#torch.manual_seed(random_seed)
x = torch.rand(1,7)
print(f"{t},{x}")
# Matrix multiply tensors
torch.matmul(t,x.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]])


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234) # I don't know whether this is deprecated


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [25]:
# Set random seed
torch.cuda.manual_seed(1234) # I don't know whether this is deprecated

# Check for access to GPU
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
print(torch.cuda.is_available())

# Create two random tensors on GPU
a = torch.random(2,2).to(device) # we don't have gpu haha
b = torch.random(2,2).to(device)

False


TypeError: 'module' object is not callable


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
t = torch.tensor([[1,2],[3,4]])
max = t.max()
max
# Find min
min = t.min()
min, max

(tensor(1), tensor(4))

### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max


# Find arg min
print(f"min:{t.argmin()},max{t.argmax()}")

min:0,max3



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
random_seed = 7
torch.manual_seed(random_seed)
# Create random tensor
t = torch.rand(1,1,1,10)

# Remove single dimensions
x= torch.squeeze(t)

# Print out tensors and their shapes
print(f"{t}, {t.shape} \n {x}, {x.shape} ")

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), torch.Size([1, 1, 1, 10]) 
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), torch.Size([10]) 
